### ISSUE TITLE
Support tagging users in tweets

### ISSUE THREAD

**Issue by arnaudj** [saasify-sh/twitter-flock#3]
As an influencer, I'd like to tag users in tweets (compared to the existing DM approach)

To confirm: do we want to do that via a 2nd account, to keep a good signal/noise ratio on the main account?

**Comment by transitive-bullshit** [comment]
Agreed.

Let's assume that the authenticated user is the one tweeting.

It's up to the influencer to decide which account they tweet from.

I'm thinking they could do:

```bash
# with main or secondary account
flock login 

flock followers export --screen-name transitive_bs -o followers.json

flock users tweet -i followers.json --template ./template.hbs
```
